Repository balancer/frontend-v2, pull requests merged in 2022-03, with the labels that each got.

#1401 Liquidity gauge contract interface
  .env.test
  package.json
  src/composables/queries/useGaugesDecorationQuery.ts
  src/composables/queries/useGaugesQuery.ts
  src/constants/queryKeys.ts
  src/lib/abi/LiquidityGaugeV5.json
  src/lib/utils/balancer/contract.ts
  src/services/balancer/contracts/contracts/liquidity-gauge.ts
  src/services/balancer/gauges/__mocks__/decorated-gauge.schema.json
  src/services/balancer/gauges/__mocks__/gauges-response.schema.json
  src/services/balancer/gauges/entities/gauges/query.ts
  src/services/balancer/gauges/gauges.decorator.ts
  src/services/balancer/gauges/types.ts
Labels: WIP

#1448 Fix console errors on trade page
  src/components/cards/PairPriceGraph/PairPriceGraph.vue
  src/components/cards/TradeCardGP/TradeCardGP.vue
  src/composables/trade/useTradeState.ts
  src/services/coingecko/api/price.service.ts
Labels: bug

#1460 Add a composable for making flexible subgraph queries
  src/composables/queries/useGraphQuery.ts
Labels: Needs review :eyes:

#1468 Confirmation indicator
  src/components/web3/ConfirmationIndicator.vue
  src/constants/queryKeys.ts
Labels: Needs review :eyes:

#1466 useTokenApprovals/Actions to support a custom spender
  src/composables/pools/useTokenApprovals.ts
  src/composables/useTokenApprovalActions.ts
Labels: Needs review :eyes:

#1465 <BalActionSteps> to accept dynamic actions
  src/components/_global/BalActionSteps/BalActionSteps.vue
Labels: Needs review :eyes:

#1447 Claim staking rewards
  src/__mocks__/transactions.ts
  src/__mocks__/vue-i18n.ts
  src/components/_global/BalAsset/BalAsset.vue
  src/components/btns/ClaimBalBtn/ClaimBalBtn.spec.ts
  src/components/btns/ClaimBalBtn/ClaimBalBtn.vue
  src/components/btns/ClaimRewardsBtn/ClaimRewardsBtn.spec.ts
  src/components/btns/ClaimRewardsBtn/ClaimRewardsBtn.vue
  src/components/btns/TxActionBtn/TxActionBtn.vue
  src/components/navs/AppNav/AppNavSettings.vue
  src/components/tables/BalClaimsTable/BalClaimsTable.vue
  src/components/tables/GaugeRewardsTable/GaugeRewardsTable.vue
  src/components/tables/PoolsTable/PoolsTable.vue
  src/components/tables/PoolsTable/TokenPills/TokenPills.vue
  src/composables/__mocks__/useNumbers.ts
  src/composables/queries/__mocks__/useGaugesDecorationQuery.ts
  src/composables/queries/__mocks__/useGaugesQuery.ts
  src/composables/queries/useGaugesDecorationQuery.ts
  src/composables/queries/useGaugesQuery.ts
  src/composables/useEthers.ts
  src/composables/usePool.ts
  src/composables/useTokenHelpers.ts
  src/constants/queryKeys.ts
  src/jest.setup.ts
  src/lib/abi/BalancerMinter.json
  src/lib/config/arbitrum.json
  src/lib/config/docker.json
  src/lib/config/homestead.json
  src/lib/config/index.ts
  src/lib/config/kovan.json
  src/lib/config/polygon.json
  src/lib/config/rinkeby.json
  src/lib/config/test.json
  src/locales/default.json
  src/pages/claim.vue
  src/plugins/router.ts
  src/services/balancer/contracts/contracts/__mocks__/balancer-minter.ts
  src/services/balancer/contracts/contracts/balancer-minter.spec.node.ts
  src/services/balancer/contracts/contracts/balancer-minter.ts
  src/services/balancer/contracts/contracts/liquidity-gauge.spec.node.ts
  src/services/balancer/contracts/contracts/liquidity-gauge.ts
  src/services/balancer/gauges/types.ts
  src/services/web3/__mocks__/web3.service.ts
  src/services/web3/web3.service.ts
Labels: Needs review :eyes:

#1451 Tokenomics - Staking Contract Implementation
  package-lock.json
  src/components/contextual/pages/pools/StakedPoolsTable.vue
  src/components/contextual/pages/pools/types.ts
  src/components/contextual/stake/StakePreview.vue
  src/components/tables/PoolsTable/PoolsTable.vue
  src/components/web3/ConfirmationIndicator.vue
  src/composables/pools/useTokenApprovals.ts
  src/composables/queries/useGraphQuery.ts
  src/composables/queries/usePoolsQuery.ts
  src/composables/queries/useUserPoolsQuery.ts
  src/composables/staking/useStaking.ts
  src/composables/useTransactions.ts
  src/constants/queryKeys.ts
  src/lib/abi/GaugeFactory.json
  src/lib/config/arbitrum.json
  src/lib/config/homestead.json
  src/lib/config/index.ts
  src/lib/config/kovan.json
  src/lib/config/polygon.json
  src/lib/config/rinkeby.json
  src/lib/config/test.json
  src/locales/default.json
  src/pages/index.vue
  src/services/balancer/contracts/contracts/liquidity-gauge.ts
  src/services/balancer/gauges/gauges-subgraph.client.spec.node.ts
  src/services/balancer/gauges/gauges-subgraph.service.spec.node.ts
  src/services/balancer/subgraph/types.ts
Labels: Needs review :eyes:

#1404 Tokenomics - Pool Page Staking Information
  src/assets/css/global/all.css
  src/components/_global/BalAccordion/BalAccordion.vue
  src/components/_global/BalBtn/BalBtn.vue
  src/components/_global/BalCard/BalCard.vue
  src/components/contextual/pages/pool/MyPoolBalancesCard.vue
  src/components/contextual/pages/pool/PoolActionsCard.vue
  src/components/contextual/pages/pool/StakingIncentivesCard/StakingIncentivesCard.vue
  src/components/contextual/pages/pools/StakedPoolsTable.vue
  src/components/contextual/pages/pools/types.ts
  src/components/contextual/stake/StakePreview.vue
  src/components/contextual/stake/StakePreviewModal.vue
  src/components/tables/PoolsTable/PoolsTable.vue
  src/composables/staking/useStaking.ts
  src/constants/symbol.keys.ts
  src/lib/utils/index.ts
  src/locales/default.json
  src/pages/index.vue
  src/pages/pool/_id.vue
  src/providers/staking.provider.ts
  src/services/balancer/contracts/contracts/liquidity-gauge.ts
  tailwind.config.js
Labels: WIP, Needs review :eyes:

#1395 Locking & Voting (Tokenomics)
  src/components/forms/lock_actions/LockForm/components/VeBalForm/components/LockEndDate.vue
  src/components/forms/lock_actions/LockForm/composables/useLockEndDate.ts
  src/composables/pools/useTokenApprovals.ts
  src/composables/useTokenApprovalActions.ts
  src/locales/default.json
Labels: WIP, Feature base
