Repository balancer/frontend-v2, pull requests merged in 2023-05, with the labels that each got.

#3292 hotfix: show metamask wallet selector in metamask mobile browser
  package-lock.json
  package.json
  src/components/web3/WalletSelectModal.vue
  src/services/web3/connectors/metamask/metamask.connector.ts
Labels: hotfix

#3316 hotfix: add unstake btn in restake flow
  package-lock.json
  package.json
  src/components/contextual/pages/pool/staking/StakingIncentivesCard.vue
Labels: hotfix

#3320 Hotfix: metamask connector logic
  package-lock.json
  package.json
  src/components/web3/WalletSelectModal.vue
  src/composables/useUserAgent.ts
  src/composables/useWalletHelpers.ts
  src/services/web3/connectors/metamask/metamask.connector.ts
Labels: hotfix

#3317 Hotfix - Ignore BalAsset tokens with undefined address
  package-lock.json
  package.json
  src/components/_global/BalAsset/BalAsset.vue
Labels: hotfix

#3361 Hotfix: Use raw tx data to submit join/exit swaps
  package-lock.json
  package.json
  src/services/balancer/pools/exits/handlers/swap-exit.handler.spec.ts
  src/services/balancer/pools/exits/handlers/swap-exit.handler.ts
  src/services/balancer/pools/joins/handlers/swap-join.handler.ts
  tests/unit/builders/signer.ts
Labels: hotfix

#3362 chore: Remove custom gas price settings
  src/services/balancer/pools/exits/exit-pool.service.ts
  src/services/balancer/pools/exits/handlers/exact-in-exit.handler.spec.ts
  src/services/balancer/pools/exits/handlers/exact-in-exit.handler.ts
  src/services/balancer/pools/exits/handlers/exact-out-exit.handler.spec.ts
  src/services/balancer/pools/exits/handlers/exact-out-exit.handler.ts
  src/services/balancer/pools/exits/handlers/exit-pool.handler.ts
  src/services/balancer/pools/exits/handlers/generalised-exit.handler.spec.ts
  src/services/balancer/pools/exits/handlers/generalised-exit.handler.ts
  src/services/balancer/pools/exits/handlers/recovery-exit.handler.spec.ts
  src/services/balancer/pools/exits/handlers/recovery-exit.handler.ts
  src/services/balancer/pools/exits/handlers/swap-exit.handler.spec.ts
  src/services/balancer/pools/exits/handlers/swap-exit.handler.ts
  src/services/balancer/pools/joins/handlers/exact-in-join.handler.spec.ts
  src/services/balancer/pools/joins/handlers/exact-in-join.handler.ts
  src/services/balancer/pools/joins/handlers/generalised-join.handler.spec.ts
  src/services/balancer/pools/joins/handlers/generalised-join.handler.ts
  src/services/balancer/pools/joins/handlers/join-pool.handler.ts
  src/services/balancer/pools/joins/handlers/swap-join.handler.ts
  src/services/balancer/pools/joins/join-pool.service.ts
  src/services/gas-price/gas-price.service.ts
  src/services/gas-price/providers/arbitrum.provider.spec.ts
  src/services/gas-price/providers/arbitrum.provider.ts
  src/services/gas-price/providers/blocknative.provider.spec.ts
  src/services/gas-price/providers/blocknative.provider.ts
  src/services/gas-price/providers/gnosis.provider.ts
  src/services/gas-price/providers/polygon.provider.ts
  src/services/gas/gas.service.spec.ts
  src/services/gas/gas.service.ts
  src/services/gas/types.ts
  src/services/web3/transactions/concerns/contract.concern.ts
  src/services/web3/transactions/concerns/raw.concern.ts
  src/services/web3/transactions/concerns/transaction.concern.ts
  src/services/web3/transactions/transaction.builder.spec.ts
Labels: Needs review :eyes:

#3363 chore: Remove legacy join/exit files
  src/components/cards/MyPoolBalancesCard/MyPoolBalancesCard.vue
  src/components/cards/MyPoolBalancesCard/components/AssetRow.vue
  src/components/contextual/pages/pool/PoolActionsCard.vue
  src/components/contextual/pages/pool/add-liquidity/AddLiquidityCard.vue
  src/components/contextual/pages/pool/add-liquidity/Page.vue
  src/components/contextual/pages/pool/withdraw/WithdrawPage.vue
  src/components/forms/pool_actions/InvestForm/InvestForm.vue
  src/components/forms/pool_actions/InvestForm/components/InvestFormTotals.vue
  src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/InvestPreviewModal.vue
  src/components/forms/pool_actions/InvestForm/components/InvestPreviewModal/components/InvestActions.vue
  src/components/forms/pool_actions/InvestForm/composables/useInvestMath.ts
  src/components/forms/pool_actions/InvestForm/composables/useInvestState.ts
  src/components/forms/pool_actions/WithdrawForm/WithdrawForm.vue
  src/components/forms/pool_actions/WithdrawForm/components/ProportionalWithdrawalInput.vue
  src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/WithdrawPreviewModal.vue
  src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActions.vue
  src/components/forms/pool_actions/WithdrawForm/components/WithdrawTotals.vue
  src/components/forms/pool_actions/WithdrawForm/components/WithdrawalTokenSelect.vue
  src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawMath.ts
  src/components/forms/pool_actions/WithdrawForm/composables/useWithdrawalState.ts
  src/composables/contextual/add-liquidity/useDisabledJoinsGuard.spec.ts
  src/composables/contextual/add-liquidity/useDisabledJoinsGuard.ts
  src/lib/utils/balancer/composableStablePoolEncoding.ts
  src/lib/utils/balancer/stablePoolEncoding.ts
  src/lib/utils/balancer/weightedPoolEncoding.ts
  src/services/pool/calculator/calculator.sevice.ts
  src/services/pool/calculator/stable.ts
  src/services/pool/calculator/weighted.ts
  src/services/pool/exchange/exchange.service.ts
  src/services/pool/exchange/serializers/ExitParams.ts
  src/services/pool/exchange/serializers/JoinParams.ts
Labels: Needs review :eyes:

#3370 chore: Rename add liquidity files
  src/components/contextual/pages/pool/add-liquidity/AddLiquidityCard.vue
  src/components/contextual/pages/pool/add-liquidity/composables/useMyWallet.spec.ts
  src/components/contextual/pages/pool/add-liquidity/composables/useMyWallet.ts
  src/components/forms/pool_actions/AddLiquidityForm/AddLiquidityForm.vue
  src/components/forms/pool_actions/AddLiquidityForm/components/AddLiquidityPreview/AddLiquidityPreview.vue
  src/components/forms/pool_actions/AddLiquidityForm/components/AddLiquidityPreview/components/Actions.vue
  src/components/forms/pool_actions/AddLiquidityForm/components/AddLiquidityPreview/components/Summary.vue
  src/components/forms/pool_actions/AddLiquidityForm/components/AddLiquidityTotals.vue
  src/components/forms/pool_actions/AddLiquidityForm/components/MissingPoolTokensAlert.vue
  src/components/forms/pool_actions/AddLiquidityForm/composables/useAddLiquidityTotals.spec.ts
  src/components/forms/pool_actions/AddLiquidityForm/composables/useAddLiquidityTotals.ts
  src/composables/pools/useAddLiquidityTabs.ts
Labels: Needs review :eyes:

#3389 Hotfix: BPT balance fetching
  package-lock.json
  package.json
  src/composables/queries/usePoolQuery.ts
Labels: hotfix

#3381 fix: Native joins on weighted pools
  src/components/cards/MyWallet/MyWallet.vue
  src/components/forms/pool_actions/AddLiquidityForm/AddLiquidityForm.vue
Labels: Needs review :eyes:

#3394 feat: Handle whale exits
  package-lock.json
  package.json
  src/components/_global/BalActionSteps/BalActionSteps.vue
  src/components/contextual/pages/vebal/LMVoting/GaugesTable.spec.ts
  src/components/forms/pool_actions/WithdrawForm/components/WithdrawPreviewModal/components/WithdrawActionsV2.vue
  src/composables/useTransactionErrors.ts
  src/constants/queryKeys.ts
  src/dependencies/balancer-sdk.mocks.ts
  src/locales/default.json
  src/providers/local/exit-pool.provider.ts
  src/services/balancer/pools/exits/exit-pool.service.ts
  src/services/balancer/pools/exits/handlers/exact-in-exit.handler.ts
  src/services/balancer/pools/exits/handlers/exact-out-exit.handler.ts
  src/services/balancer/pools/exits/handlers/exit-pool.handler.ts
  src/services/balancer/pools/exits/handlers/generalised-exit.handler.spec.ts
  src/services/balancer/pools/exits/handlers/generalised-exit.handler.ts
  src/services/balancer/pools/exits/handlers/recovery-exit.handler.spec.ts
  src/services/balancer/pools/exits/handlers/recovery-exit.handler.ts
  src/services/balancer/pools/exits/handlers/swap-exit.handler.ts
Labels: high priority

#3397 Hotfix: Add hosted graph app alert
  package-lock.json
  package.json
  src/App.vue
Labels: hotfix
